name: Build Maximo Labs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Install Python 3.9.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
          
      - run: pip list
      - run: pip install mkdocs ghp-import
      - run: pip list

      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
